config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'static#home'

  get 'about' => 'static#about'
  get 'home' => 'static#home'
  get 'contact' => 'static#contact'

  resources :comments

  resources :articles

  resources :users

  resources :sessions, :only => [:new, :create, :destroy]

  get '/signup'=> 'users#new'
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'

  get '*' => 'static#not_found'
  get '/not_found' => 'static#not_found'

end

app/views/layouts/_footer.html.erb
<footer>
	<ul>
		<li>Site réalisé avec Rails</li>
		<li><%= link_to "Contact", contact_path %></li>
	</ul>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>Japantaku | <%= @title %> </title>

  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'basic', media: 'screen' %>
  <%= stylesheet_link_tag @css_current, media: 'screen' %>

  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
</head>

app/views/layouts/_navi.html.erb
<header>
	<% if !current_user.nil? then %> Bienvenue bg de <%= current_user.pseudo %> !<% end %>
	<% if !current_user.nil? then %><%= link_to "Se déconnecter", signout_path %><% end %>
	<nav>
		<ul>
			<!-- Pour les visiteurs -->
			<li><%= link_to "Accueil", root_path %></li>
			<li>Nos voyages</li>
			<li>Photos & vidéos</li>
			<li>Coups de coeurs</li>
			<li>Conventions</li>
			<li>Recherche</li>
			<li><%= link_to "À Propos", about_path %></li>

			<!-- Pour les utilisateurs -->
			<% if signed_in? %>
				<li><%= link_to "Créer un article", new_article_path %></li>
				<li><%= link_to "Mon profil", user_path(current_user)%></li>
			<% end %>

			<!-- Pour les admins -->
			<% if is_admin? %>
				<li>Interface de gestion</li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<%= render 'layouts/head' %>

	<body>
		<div class="container">
			<%= render 'layouts/navi' %>

			<section>
			  <% flash.each do |key, value| %>
			    <div class="flash <%= key %>"><%= value %></div>
			  <% end %>
			  <%= yield %>
			</section>

			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>